src/decoders/fp_dng.cpp: rename swap functions
The swap32() function conflicts with a macro on OpenBSD.

src/decoders/fp_dng.cpp:575:26: error: too many arguments provided to function-like macro invocation
void swap32(uchar *data, int len)
                         ^
/usr/include/sys/endian.h:71:9: note: macro 'swap32' defined here
        ^