Added space before DCRAW_VERSION to prevent MS VS compiler errors
Without the space, the following compiler error occurs in Visual Studio (confirmed with 2013 and 2015; 2008 worked fine).

1>D:\[..]\src\FreeImage\Source\LibRawLite\internal\dcraw_common.cpp(14590): error C3688: invalid literal suffix 'DCRAW_VERSION'; literal operator or literal operator template 'operator ""DCRAW_VERSION' not found
1>D:\[..]\src\FreeImage\Source\LibRawLite\internal\dcraw_common.cpp(14590): error C2660: 'strcpy': function does not take 1 arguments

Please ignore the different code line numbers, since the build output is from LibRaw 0.18.0.201511